CONSUMER_KEY = 'kE8Z0aseFrs8mj0MpasTPh45t'
# CONSUMER_KEY = os.getenv("CONSUMER_KEY", None)
CONSUMER_SECRET = '6I9Re4zMB8XVPyfWQHlbkNtHiFF51pGnfjy0scCXSUl4oT7qrg'
# CONSUMER_SECRET = os.getenv("CONSUMER_SECRET", None)
ACCESS_TOKEN = '84566636-r4PB7qdMTrh86rooibgyJmDZjXJOLEEkvpN3wE4bT'
# ACCESS_TOKEN = os.getenv("ACCESS_TOKEN", None)
ACCESS_TOKEN_SECRET = '0iiPPqH4k9EylmeVQimmIk64U0ofDFLBBekK6OefKxenr'